spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    remote:
      restart:
        enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    com.example.preventduplicatelogin: debug
